language: php

php:
    - 5.4
    - 5.5
    - hhvm

env:
    -
      SYMFONY_VERSION="2.3.*"
      REACT_VERSION="0.4.*"
    -
      SYMFONY_VERSION="2.5.*"
      REACT_VERSION="0.4.*"
    -
      SYMFONY_VERSION="2.5.*"
      REACT_VERSION="0.3.*"
    -
      SYMFONY_VERSION="dev-master"
      REACT_VERSION="dev-master"

matrix:
    allow_failures:
        - php: hhvm
        - env: SYMFONY_VERSION="dev-master"
        - env: REACT_VERSION="dev-master"

install:
    - composer self-update
    - composer require react/event-loop:${REACT_VERSION} --no-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/monolog-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/console:${SYMFONY_VERSION} --no-update
    - composer require symfony/finder:${SYMFONY_VERSION} --no-update
    - composer install --dev --prefer-source

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text